# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for MCP OpenSearch JS Server
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy source files
COPY . .

# Expose stdio, no port
# Final image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy installed dependencies and source from build stage
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app .

# Ensure environment variables are used for configuration
# Default command
CMD ["node", "index.js"]
